-- Add order_number column to orders table
-- This will be automatically incremented for each new order.

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'orders' AND column_name = 'order_number'
    ) THEN
        ALTER TABLE orders ADD COLUMN order_number BIGINT GENERATED BY DEFAULT AS IDENTITY;
    END IF;
END $$;
